name: rpic
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - python=3.8.3
  - black
  - requests
  - mypy
  - pip
  - isort
  - pytest
  - flake8
  - wxpython
  - pip:
    - pubsub
